### PR TITLE
Remove dependecy on 'fs'

### PR DESCRIPTION
**Pull request by olaven**
The use of [Request](https://yarnpkg.com/en/package/request) made this package transitively dependent on [fs](https://nodejs.org/api/fs.html). This was a problem for me because `fs` is not available in browser environments. 

I have rewritten the library to use the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead. This way, `pdf-shift` should be usable both server- and client side 😄

### CODE REVIEW

**Comment by cnicodeme** [comment]
Hi!

Thank you very much for your PR. This is an interesting approach and I like it.

Unfortunately I tried to make it work on server side (using Node) and had multiple issues:

 * btoa is not defined
 * Fetch is not available too.

For `btoa`, I added the following (while testing):

```js
    btoa: function(value) {
        if (typeof btoa !== 'undefined') {
            return btoa(value)
        }

        return Buffer.from(value).toString('base64')
    }
```

And call this.btoa on the fetch call.

But fot the "Fetch" issue, I don't know. Do you have any ideas?

(note: I won't be available the next two weeks so don't worry if I don't reply fast).

Thank you!

**Comment by olaven** [comment]
Thank you, I am glad to hear that you liked the approach! 

I am surprised that `fetch` was not available and will investigate further as  soon as I have some time to spare. I'll figure something out :-)

**Comment by olaven** [comment]
Okay: 

* `btoa` is totally my bad. It appears to be a method on the global `window`. It therefore makes sense that it did not work in Node. I am not sure why it worked with NextJS.. Anyways, it seems like your `Buffer.from(value).toString('base64')`is the proper way to do it in Node 😄 
* I also replaced `fetch` with [cross-fetch](https://github.com/lquixada/cross-fetch) for compatibility

**Comment by cnicodeme** [comment]
Thank @olaven for your push request, and sorry for the delay.

I've run some tests but I'm still having issues. I'll see to fix these tomorrow and also find a way to have the "cross-fetch" package automatically loaded when it's not present (when in the browser). I'll let you know :)

**Comment by olaven** [comment]
Thank you, and no worries :)

**Comment by cnicodeme** [comment]
I (finally) accepted the PR, but I initiall worked on it to use "require" only on node environment. I also modified a bit the code in some parts. I think it's nice now.

Thank you for your help and your patience!

Don't hesitate if you have any remarks on the changes!

**Comment by olaven** [comment]
Thank you for taking the time to review and improve it! 😄

**Comment by cnicodeme** [comment]
Emphasis on "taking the time" 😁

Thank you for helping me improve the service 🙂

Le jeu. 19 sept. 2019 à 21:56, Olav Sundfør <notifications@github.com> a
écrit :

**Pull request merged**
